# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getParamsEP_priorMean_algo1_cpp <- function(X, y, priorMean, nu2, tolerance, maxIter = 1e6L) {
    .Call(`_EPmvnCDF_getParamsEP_priorMean_algo1_cpp`, X, y, priorMean, nu2, tolerance, maxIter)
}

getParamsEP_priorMean_priorVar_algo1_cpp <- function(X, y, priorMean, priorVariances, tolerance, maxIter = 1e6L) {
    .Call(`_EPmvnCDF_getParamsEP_priorMean_priorVar_algo1_cpp`, X, y, priorMean, priorVariances, tolerance, maxIter)
}

getParamsEP_priorMean_cpp <- function(X, y, priorMean, nu2, tolerance, maxIter = 1e6L) {
    .Call(`_EPmvnCDF_getParamsEP_priorMean_cpp`, X, y, priorMean, nu2, tolerance, maxIter)
}

getParamsEP_priorMean_priorVar_cpp <- function(X, y, priorMean, priorVariances, tolerance, maxIter = 1e6L) {
    .Call(`_EPmvnCDF_getParamsEP_priorMean_priorVar_cpp`, X, y, priorMean, priorVariances, tolerance, maxIter)
}

